export const posts = [
  {
    id: "1",
    billboardId: "TLV",
    title: "Looking for drummer",
    details: "Need drummer for Jazz band",
    likeIds: [],
  },
  {
    id: "2",
    billboardId: "BRS",
    title: "Room for jam",
    details: "Available studio room tomorrow evening",
    likeIds: [],
  },
  {
    id: "3",
    billboardId: "BRS",
    title: "Room for jam",
    details: "Available studio room tomorrow evening",
    likeIds: [],
  },
  {
    id: "4",
    billboardId: "BRS",
    title: "Room for jam",
    details: "Available studio room tomorrow evening",
    likeIds: [],
  },
  {
    id: "5",
    billboardId: "BRS",
    title: "Room for jam",
    details: "Available studio room tomorrow evening",
    likeIds: [],
  },
  {
    id: "6",
    billboardId: "BRS",
    title: "Room for jam",
    details: "Available studio room tomorrow evening",
    likeIds: [],
  },
  {
    id: "7",
    billboardId: "BRS",
    title: "Room for jam",
    details: "Available studio room tomorrow evening",
    likeIds: [],
  },
  {
    id: "8",
    billboardId: "BRS",
    title: "Room for jam",
    details: "Available studio room tomorrow evening",
    likeIds: [],
  },
  {
    id: "9",
    billboardId: "BRS",
    title: "Room for jam",
    details: "Available studio room tomorrow evening",
    likeIds: [],
  },
  {
    id: "10",
    billboardId: "TLV",
    title: "Guitar player needed",
    details: "Rock band looking for lead guitar",
    likeIds: [],
  },
  {
    id: "11",
    userId: 1,
    billboardId: "BRC",
    title: "Guitar player needed",
    details: "Rock band looking for lead guitar",
    imageUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Z3VpdGFyfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    postDate: new Date("2026-01-15"),
    likeIds: [1, 2, 3],
    commentIds: ['1', '2'],
  },
  {
    id: "12",
    userId: 2,
    billboardId: "BRC",
    title: "Guitar player needed",
    details: "Rock band looking for lead guitar",
    imageUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Z3VpdGFyfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    postDate: new Date("2026-01-15"),
    likeIds: [1, 2, 3],
    commentIds: ['1', '2'],
  },
];
