export const tasks = [
  {
    id: 1,
    bandId: 1,
    name: "Book rehearsal room",
    details: "Contact Groove Studio for next week session",
    owners: [1, 2],
    assignDate: "2026-01-23T14:32:10.123Z",
    done: false,
  },
  {
    id: 2,
    bandId: 1,
    name: "Book rehearsal room",
    details: "Contact Groove Studio for next week session",
    owners: [3, 2],
    assignDate: "2026-01-23T14:32:10.123Z",
    done: false,
  },
  {
    id: 3,
    bandId: 2,
    name: "Book rehearsal room",
    details: "Contact Groove Studio for next week session",
    owners: [1],
    assignDate: "2026-01-23T14:32:10.123Z",
    done: false,
  },
  {
    id: 4,
    bandId: 2,
    name: "Book rehearsal room",
    details: "Contact Groove Studio for next week session",
    owners: [1],
    assignDate: "2026-01-23T14:32:10.123Z",
    done: false,
  },
];
